version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dapeps_db
      POSTGRES_USER: anda
      POSTGRES_PASSWORD: anda123
    ports:
      - "5432:5432"
